# -*- coding: utf-8 -*-
"""s30338_zadanie3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11F8aP_0Af4N6xspfSWG1SWRhgSBC-YIP

Zadanie 3: Analiza jakości danych NGS - reimplementacja FastQC
Kontrola jakości (QC) jest pierwszym i bardzo ważnym krokiem każdej analizy NGS. Zgodnie z maksymą GIGO złe dane = złe wyniki! Program FastQC jest standardem branżowym do QC danych z sekwencjonowania. Zamiast tylko uruchamiać FastQC, Twoim zadaniem jest ZROZUMIEĆ jak działa i samodzielnie zaimplementować w Pythonie dwa z jego wykresów. Ten film może pomóc Ci zrozumieć wykresy.

#Część pierwsza: Podstawowa analiza pliku FASTQ
Napisz skrypt w Pythonie z następującymi wymaganiami:

1. Wczytaj plik FASTQ.gz:
sample_data.fastq.gz : https://drive.google.com/file/d/1ur0-5pgRM2_OozF4CFo2Y7dfHwthl1s3/view?usp=sharing

   UWAGA: Plik jest skompresowany! Użyj odpowiedniej biblioteki python do odczytu.
2. Parsuj plik FASTQ i dla każdego odczytu wyciągnij:
  
    a) Sekwencję nukleotydów (linia 2)
    b) Quality scores (linia 4)

3. Oblicz i wyświetl podstawowe statystyki:
    a. Całkowita liczba odczytów
    b. Długość odczytów (jeśli stała - podaj długość, jeśli różne - podaj min, max, średnią)
    c. Średnia jakość wszystkich nukleotydów w pliku:
    d. % odczytów z średnią jakością > 30
    e. % odczytów z średnią jakością > 20

Przykładowy output:
=== ANALIZA PLIKU FASTQ ===

Plik: sample_data.fastq.gz
Liczba odczytów: 10000
Długość odczytów: 150 bp

Statystyki jakości:
  Średnia jakość: 34.2
  Odczyty z Q > 30: 8543 (85.4%)
  Odczyty z Q > 20: 9876 (98.8%)
"""

import gzip

# Generator zwracający (sequence, quality) dla każdego odczytu
def parse_fastq(filename):
    with gzip.open(filename, 'rt') as f:
        while True:
            header = f.readline().strip()  # linia 1: @ID
            if not header:
                break
            seq = f.readline().strip()      # linia 2: sekwencja
            plus = f.readline().strip()     # linia 3: +
            qual = f.readline().strip()     # linia 4: jakość
            yield seq, qual

# Konwertuje string jakości na listę Phred scores
def quality_to_phred(quality_string):
    return [ord(char) - 33 for char in quality_string]

"""1. Wczytaj plik FASTQ.gz:
sample_data.fastq.gz : https://drive.google.com/file/d/1ur0-5pgRM2_OozF4CFo2Y7dfHwthl1s3/view?usp=sharing

   UWAGA: Plik jest skompresowany! Użyj odpowiedniej biblioteki python do odczytu.
"""

import numpy as np

sciezka = "sample_data.fastq.gz"

total_reads = 0
read_lengths = []
all_qualities = []
reads_q30 = 0
reads_q20 = 0

#analiza FASTQ
for seq, qual in parse_fastq(sciezka):
  total_reads += 1
  read_lengths.append(len(seq))

  phred_scores = quality_to_phred(qual)
  all_qualities.extend(phred_scores)

  mean_read_quality = np.mean(phred_scores)

  if mean_read_quality>30:
    reads_q30 += 1
  if mean_read_quality>20:
    reads_q20 += 1


#statystyki dlugosci
min_length = min(read_lengths)
max_length = max(read_lengths)
mean_length = np.mean(read_lengths)

mean_file_quality = np.mean(all_qualities)

percent_q30 = (reads_q30/total_reads)*100
percent_q20 = (reads_q20/total_reads)*100

print("=== ANALIZA PLIKU FASTQ ===\n")

print(f"Plik: {sciezka}")
print(f"Liczba odczytów: {total_reads}")
print(f"Długość odczytów: {mean_length} bp\n")

print("Statystyki jakości:")
print(f"  Średnia jakość: {mean_file_quality}")
print(f"  Odczyty z Q > 30: {reads_q30} ({percent_q30:.1f}%)")
print(f"  Odczyty z Q > 20: {reads_q20} ({percent_q20:.1f}%)\n")

"""Część druga: Reimplementacja wykresu FastQC

Wykres 1: "Per Base Sequence Quality"

Odtwórz wykres FastQC pokazujący jakość na każdej pozycji w odczycie.
1. Dla każdej pozycji w odczycie (1 do długości):
    a. Zbierz quality scores ze wszystkich odczytów
    b. Oblicz: percentyl 10, 25, medianę, 75, 90
2. Stwórz wykres podobny do FastQC:
    a. Oś X: pozycja w odczycie (1-150)
    b. Oś Y: Phred quality score (0-40)
    c. Boxplot dla każdej pozycji (matplotlib.pyplot.boxplot lub seaborn)
    d. Alternatywnie: wykres liniowy z medianą + zakresami
3. Dodaj strefy jakości (tło):
    a. Zielone tło: Q > 28 (dobra jakość)
    b. Pomarańczowe: Q 20-28 (średnia)
    c. Czerwone: Q < 20 (zła)
4. Zapisz wykres: per_base_quality.png
5. INTERPRETACJA - odpowiedz:
  Q1: Jak zmienia się jakość wzdłuż odczytu?
  A1:


"""

import matplotlib.pyplot as plt

quality_per_position = []

for seq, qual in parse_fastq(sciezka):
  phred_scores = quality_to_phred(qual)

  if len(quality_per_position) == 0:
    for i in range(len(phred_scores)):
      quality_per_position.append([])

  for i, score in enumerate(phred_scores):
    quality_per_position[i].append(score)

#statystyki dla pozycji
positions = []
medians = []
p10 = []
p25 = []
p75 = []
p90 = []

for i, scores in enumerate(quality_per_position):
  positions.append(i+1)
  medians.append(np.median(scores))
  p10.append(np.percentile(scores, 10))
  p25.append(np.percentile(scores, 25))
  p75.append(np.percentile(scores,75))
  p90.append(np.percentile(scores,90))

#wykres
plt.figure(figsize=(10, 6))

plt.axhspan(28, 40, color="green", alpha=0.2)
plt.axhspan(20, 28, color= "orange", alpha = 0.2)
plt.axhspan(0,20, color = "red", alpha = 0.2)

#zakres 10-90
plt.fill_between(
    positions,
    p10,
    p90,
    color = 'yellow',
    alpha = 0.4,
    label = 'P10-P90'
)

#zakres IQR
plt.fill_between(
    positions,
    p25,
    p75,
    color = 'green',
    alpha = 0.5,
    label = 'P25-P75'
)

#mediana
plt.plot(
    positions,
    medians,
    color = 'black',
    linewidth = 2,
    label = 'Median'
)

#opisy
plt.xlabel('Pozycja w odczycie')
plt.ylabel('Phred Quality Score')
plt.title('Per Base Sequence Quality')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig('per_base_quality.png')
plt.show()

"""INTERPRETACJA - odpowiedz:
   # Q1: Jak zmienia się jakość wzdłuż odczytu?

  # A1: Jakość jest wysoka na wiekszej czcesci dlugosci odczytu, w dalszej czesci sa lokalne spadki. ogolna jakosc danych dobra, bo wiekszosc pozycji pozostaje w zielonej strefie > 28
"""