# -*- coding: utf-8 -*-
"""s30338_zadanie2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bX2lbG2C6zBM5-ks15qDyG1pk1l3jdhw

Zestaw danych jest niezbalansowany - zawiera więcej przypadków benign (63%) niż malignant (37%). To ma znaczenie dla analizy!

Napisz skrypt w Pythonie z następującymi wymaganiami:

1. Załaduj dane używając sklearn

2. Podziel dane na zbiór treningowy (80%) i testowy (20%). UWAGA: Na razie użyj ZWYKŁEGO split (bez stratify). Użyj random_state=42

3. Wytrenuj dwa modele klasyfikacji:

    a) Logistic Regression

    b) Random Forest Classifier (n_estimators=100)

4. Dla każdego modelu oblicz i wyświetl metryki:
    a) accuracy (dokładność)
    b) precision (precyzja)
    c) recall (czułość)
    d) f1-score

5. Dla każdego modelu narysuj confusion matrix i zapisz do pliku PNG

WAŻNE: Wyświetl rozkład klas w zbiorze treningowym i testowym.


Przykładowy output:
=== WISCONSIN BREAST CANCER - KLASYFIKACJA ===

Wczytano dane: 569 próbek, 30 cech

Rozkład klas w pełnym datasecie:
  Benign (1): 357 (62.7%)
  Malignant (0): 212 (37.3%)

Podział danych: 455 treningowych, 114 testowych

Rozkład klas w zbiorze treningowym:
  Benign: 64.2%
  Malignant: 35.8%

Rozkład klas w zbiorze testowym:
  Benign: 56.1%
  Malignant: 43.9%

=== LOGISTIC REGRESSION ===

Accuracy: 0.96
Precision: 0.95
Recall: 0.98
F1-score: 0.96
Confusion matrix zapisana: confusion_matrix_lr.png

=== RANDOM FOREST ===

Accuracy: 0.95
Precision: 0.94
Recall: 0.97
F1-score: 0.95
Confusion matrix zapisana: confusion_matrix_rf.png
"""

#pip install scikit-learn pandas numpy
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np

# Załaduj dane
data = load_breast_cancer()
X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target, name='diagnosis')  # 0=malignant, 1=benign

print("=== WISCONSIN BREAST CANCER - KLASYFIKACJA ===\n")

# Wyświetl informacje o danych
print(f"Wczytano dane: {len(X)} probek, {X.shape[1]} cech\n")
print(f"Rozkład klas w pelnym datasecie:")
print(f"  Benign (1): {sum(y==1)} ({sum(y==1)/len(y)*100:.1f}%)")
print(f"  Malignant (0): {sum(y==0)} ({sum(y==0)/len(y)*100:.1f}%)")

"""Zestaw danych jest niezbalansowany - zawiera więcej przypadków benign (63%) niż malignant (37%). To ma znaczenie dla analizy!

2. Podziel dane na zbiór treningowy (80%) i testowy (20%). UWAGA: Na razie użyj ZWYKŁEGO split (bez stratify). Użyj random_state=42
"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Podział danych: {len(x_train)} treningowych, {len(x_test)} testowych")

print("\nRozkład klas w zbiorze treningowym:")
print(f"  Benign: {sum(y_train==1)/len(y_train)*100:.1f}%")
print(f"  Malignant: {sum(y_train==0)/len(y_train)*100:.1f}%")

print("\nRozkład klas w zbiorze testowym:")
print(f"  Benign: {sum(y_test==1)/len(y_test)*100:.1f}%")
print(f"  Malignant: {sum(y_test==0)/len(y_test)*100:.1f}%")

"""3. Wytrenuj dwa modele klasyfikacji:

    a) Logistic Regression
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
  accuracy_score,
  precision_score,
  recall_score,
  f1_score,
  confusion_matrix,
  ConfusionMatrixDisplay
)
import matplotlib.pyplot as plt

#model
lregr = LogisticRegression(max_iter=10000)#dla pewnosci ze zdazy sie nauczyc

#trenowanie
lregr.fit(x_train, y_train)

#predykcja
y_pred_lr = lregr.predict(x_test)

#metryki
accuracy_lr = accuracy_score(y_test, y_pred_lr)
precision_lr = precision_score(y_test, y_pred_lr)
recall_lr = recall_score(y_test, y_pred_lr)
f1_lr = f1_score(y_test, y_pred_lr)

"""3. Wytrenuj dwa modele klasyfikacji:

    b) Random Forest Classifier (n_estimators=100)
"""

from sklearn.ensemble import RandomForestClassifier

#mdoel
forest = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    max_depth=3
)

#trenowanie
forest.fit(x_train, y_train)

#predykcja
y_pred_rf = forest.predict(x_test)

#metryki
accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)

"""4. Dla każdego modelu oblicz i wyświetl metryki:
    a) accuracy (dokładność)
    b) precision (precyzja)
    c) recall (czułość)
    d) f1-score
"""

print("\n=== LOGISTIC REGRESSION ===")
print(f"Accuracy: {accuracy_lr:.2f}")
print(f"Precision: {precision_lr:.2f}")
print(f"Recall: {recall_lr:.2f}")
print(f"F1-score: {f1_lr:.2f}")

cm_lr = confusion_matrix(y_test, y_pred_lr)
disp_lr = ConfusionMatrixDisplay(
    confusion_matrix=cm_lr,
    display_labels = ["Malignant", "Benign"]
)

print("\n=== RANDOM FOREST ===")
print(f"Accuracy: {accuracy_rf:.2f}")
print(f"Precision: {precision_rf:.2f}")
print(f"Recall: {recall_rf:.2f}")
print(f"F1-score: {f1_rf:.2f}")

cm_rf = confusion_matrix(y_test, y_pred_rf)
disp_rf = ConfusionMatrixDisplay(
    confusion_matrix=cm_rf,
    display_labels = ["Malignant", "Benign"]
)

"""5. Dla każdego modelu narysuj confusion matrix i zapisz do pliku PNG

WAŻNE: Wyświetl rozkład klas w zbiorze treningowym i testowym.
"""

disp_lr.plot(cmap = "Blues")
plt.title("Confusion Matrix - Logistic Regression")
plt.savefig("confusion_matrix_lr.png")
plt.show()
print("\nConfusion matrix zapisana: confusion_matrix_lr.png")

disp_rf.plot(cmap = "Reds")
plt.title("Confusion Matrix - Random Forest")
plt.savefig("confusion_matrix_rf.png")
plt.show()
print("Confusion matrix zapisana: confusion_matrix_rf.png")